// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd8sKjjKMYWIYZo_I_AcaC-64MfXLLQJ0',
    appId: '1:605678286689:android:3f7892d92caf6117147720',
    messagingSenderId: '605678286689',
    projectId: 'pharacyversiontow',
    storageBucket: 'pharacyversiontow.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYXq2EDCmoIRUGL93AB_krleVZVhtokRg',
    appId: '1:605678286689:web:84be9016b5f563ee147720',
    messagingSenderId: '605678286689',
    projectId: 'pharacyversiontow',
    authDomain: 'pharacyversiontow.firebaseapp.com',
    storageBucket: 'pharacyversiontow.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrweaNdVBvPZ2VIxH9AVPXX_x6f1Xl9xg',
    appId: '1:605678286689:ios:6ee9a53b89b3325d147720',
    messagingSenderId: '605678286689',
    projectId: 'pharacyversiontow',
    storageBucket: 'pharacyversiontow.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyversiontow',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrweaNdVBvPZ2VIxH9AVPXX_x6f1Xl9xg',
    appId: '1:605678286689:ios:6ee9a53b89b3325d147720',
    messagingSenderId: '605678286689',
    projectId: 'pharacyversiontow',
    storageBucket: 'pharacyversiontow.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyversiontow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYXq2EDCmoIRUGL93AB_krleVZVhtokRg',
    appId: '1:605678286689:web:84a59402f54446c7147720',
    messagingSenderId: '605678286689',
    projectId: 'pharacyversiontow',
    authDomain: 'pharacyversiontow.firebaseapp.com',
    storageBucket: 'pharacyversiontow.firebasestorage.app',
  );

}